name: CI-web-app

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'apps/web-app/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    # Optional:
    #   Only consider those files/paths to trigger the github action
    #   to prevent unnecessary builds.
    paths:
      - 'apps/web-app/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Why not using setup-node 2.2+ cache option (yet) ?
      # see https://github.com/belgattitude/nextjs-monorepo-example/pull/369
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      # To keep the custom cache from infinitely growing
      - name: Get week cache identifier
        id: get-week
        run: echo ::set-output name=WEEK::$(date +%U)

      - name: Restore web-app caches
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/apps/web-app/.next/cache
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
            ${{ github.workspace }}/**/.eslintcache
          key: web-app-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-${{ steps.get-week.outputs.WEEK }}-${{ github.sha }}
          restore-keys: |
            web-app-${{ runner.os }}-${{ github.job }}-
            web-app-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-${{ steps.get-week.outputs.WEEK }}-

      - name: Install dependencies
        run: |
          yarn install --immutable
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Typecheck
        working-directory: apps/web-app
        run: |
          yarn typecheck

      - name: Linter
        working-directory: apps/web-app
        run: |
          yarn lint --cache

      - name: Unit tests
        working-directory: apps/web-app
        run: |
          yarn test-unit --runInBand --color

      - name: Build web-app
        working-directory: apps/web-app
        run: |
          yarn build
        env:
          # Speed up build: they are linted in a previous step
          NEXTJS_IGNORE_ESLINT: 1
          # Speed up build: they are typechecked in a previous step
          NEXTJS_IGNORE_TYPECHECK: 1
          # Speed up build: don't run if not needed, enable if it becomes needed
          NEXT_DISABLE_SOURCEMAPS: 1
          # Don't send telemetry for ci
          NEXT_TELEMETRY_DISABLED: 1
          # Fully disable sentry registration here (no overhead in build time)
          NEXT_DISABLE_SENTRY: 1
          # Disable sentry source map upload (when not needed)
          NEXT_SENTRY_DRY_RUN: 1

      - name: Check bundle size
        working-directory: apps/web-app
        run: |
          yarn check-build-size

      - name: Check ecmascript checks for build files
        working-directory: apps/web-app
        run: |
          yarn check-dist
